FROM golang:1.25.0-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY api ./api
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -o /quality-controller ./cmd/quality-controller

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /quality-controller /quality-controller
USER nonroot:nonroot
ENTRYPOINT ["/quality-controller"]
