apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - edgecdnx
  - mediamtx
  - hls/edge/overlays/edge-syd-a
  - hls/edge/overlays/edge-syd-b
  - hls/edge/overlays/edge-sin-a
  - monitoring/servicemonitors.yaml
  - quality-controller.yaml
