apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: DNSEndpoint
metadata:
  name: geolocation-demo
  namespace: edgecdnx
spec:
  dnsName: app.example.com
  routingPolicy: Geolocation
  recordTTL: 60
  recordType: A
  routeSelector:
    matchLabels:
      project: tbotech
---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Location
metadata:
  name: us-east
  labels:
    edgecdnx.com/routing-instance: edgecdnx
    project: tbotech
    edgecdnx.com/region: us-east
spec:
  weight: 100
  geoLookup:
    weight: 100
    attributes:
      geoip/continent/code:
        weight: 1000
        values:
          - value: NA
          - value: SA
  fallbackLocations:
    - eu-central
  nodeGroups:
    - name: default
      healthCheck:
        name: healthcheckprofile
      flavor: ""
      nodes:
        - name: us-east-node-1
          ipv4: 74.220.24.46
      labels:
        region: us-east
---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Location
metadata:
  name: eu-central
  labels:
    edgecdnx.com/routing-instance: edgecdnx
    project: tbotech
    edgecdnx.com/region: eu-central
spec:
  weight: 100
  geoLookup:
    weight: 100
    attributes:
      default:
        weight: 1
      geoip/continent/code:
        weight: 1000
        values:
          - value: EU
          - value: AF
          - value: AS
  fallbackLocations:
    - us-east
  nodeGroups:
    - name: default
      healthCheck:
        name: healthcheckprofile
      flavor: ""
      nodes:
        - name: eu-central-node-1
          ipv4: 74.220.31.183
      labels:
        region: eu-central
