grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 2h
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
